name: Deploy Azure Functions ETL

on:
  push:
    branches:
      - main
    paths:
      - 'functions-etl/**'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_4A85A3B9859549F3A0E2E8D739D65B02 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_8446C824F8F5419B8E5EEC38CBD04DCF }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_78629AE3D9884F2599A44AD0578F8B98 }}

      - name: Deploy to Azure Functions (with remote Oryx build)
        uses: Azure/functions-action@v1
        with:
          app-name: 'func-projeto-b3'
          package: './functions-etl'
          enable-oryx-build: true
          scm-do-build-during-deployment: true
          remote-build: true
          respect-funcignore: true

      - name: Restart Function App
        run: |
          az functionapp restart --name func-projeto-b3 --resource-group rg-projeto-b3